import { describe, it, expect } from 'vitest';
import { execa } from 'execa';
import { readFileSync, existsSync } from 'node:fs';
import { resolve, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const reqFile = resolve(__dirname, '..', 'requirements-mcp.txt');

describe('MAF agent-framework install (W442-T1)', () => {
  it('agent_framework module imports cleanly in Z:/venvs/claude', async () => {
    const result = await execa(
      'Z:/venvs/claude/Scripts/python.exe',
      ['-c', 'import agent_framework; print(agent_framework.__name__)'],
      { reject: false }
    );
    expect(result.exitCode).toBe(0);
    expect(result.stdout).toContain('agent_framework');
  });

  it('MCPStdioTool class is importable from agent_framework', async () => {
    const result = await execa(
      'Z:/venvs/claude/Scripts/python.exe',
      ['-c', 'from agent_framework import MCPStdioTool; print(MCPStdioTool.__name__)'],
      { reject: false }
    );
    expect(result.exitCode).toBe(0);
    expect(result.stdout).toBe('MCPStdioTool');
  });

  it.skipIf(!existsSync(reqFile))('requirements-mcp.txt exists and is pip-compile-generated', () => {
    const content = readFileSync(reqFile, 'utf8');
    expect(content).toMatch(/# This file is autogenerated by pip-compile/);
    expect(content).toMatch(/agent-framework==/);
  });
});
